mq_demo: mq_demo.cpp
	g++ -std=c++11 -o mq_demo mq_demo.cpp -lpthread &&\
	g++ -std=c++11 -o mq_tmpl mq_tmpl.cpp -lpthread &&\
	g++ -std=c++11 -o main main.cpp -lpthread
clean:
	rm -f mq_demo mq_tmpl main